title: Normal One   # your title
author: Wennn # your name
description: 不以物喜，不以己悲 # your description
avatar: /images/avatar.jpg # change avatar

# Build Settings
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 5
paginate_path: "/page:num/"
gems: [jekyll-paginate]
